EMR/urls.py
# from django.conf.urls.defaults import patterns, include
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from formdemografi import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('formdemografi.urls', namespace="formdemografi")),
]

formdemografi/urls.py
from django.conf.urls import url

from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import views

from .views import PatientCreateView, PatientListView, PatientUpdateView, PatientDetailView
from .views import LocationCreateView, LocationListView, LocationUpdateView, LocationDetailView
from .views import ConditionCreateView, ConditionListView, ConditionUpdateView, ConditionDetailView
from .views import EncounterCreateView, EncounterListView, EncounterUpdateView, EncounterDetailView
from .views import CodeableConceptCreateView, CodeableConceptListView, CodeableConceptUpdateView, CodeableConceptDetailView
from .views import PractitionerCreateView, PractitionerListView, PractitionerUpdateView, PractitionerDetailView
from .views import HealthcareServiceCreateView, HealthcareServiceListView, HealthcareServiceUpdateView, HealthcareServiceDetailView
from .views import DiagnosticReportCreateView, DiagnosticReportListView, DiagnosticReportUpdateView, DiagnosticReportDetailView
# from .views import StatusDokterListView
from .views import daftarTabelListView
# from .views import PatientSearchListView
# from .views import search
urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),

    url(r'^codeableconcept/$', CodeableConceptListView.as_view(), name='codeableconcept_list'),
    url(r'^codeableconcept/new/$', CodeableConceptCreateView.as_view(), name='codeableconcept_add'),
    url(r'^codeableconcept/(?P<pk>\d+)/update/$', CodeableConceptUpdateView.as_view(), name='codeableconcept_update'),
    # url(r'^codeableconcept/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='codeableconcept_detail'),

    url(r'^condition/$', ConditionListView.as_view(), name='condition_list'),
    url(r'^condition/new/$', ConditionCreateView.as_view(), name='condition_add'),
    url(r'^condition/(?P<pk>\d+)/update/$', ConditionUpdateView.as_view(), name='condition_update'),
    url(r'^condition/(?P<pk>\d+)/detail/$', ConditionDetailView.as_view(), name='condition_detail'),

    url(r'^diagnosticreport/$', DiagnosticReportListView.as_view(), name='diagnosticreport_list'),
    url(r'^diagnosticreport/new/$', DiagnosticReportCreateView.as_view(), name='diagnosticReport_add'),
    url(r'^diagnosticreport/(?P<pk>\d+)/update/$', DiagnosticReportUpdateView.as_view(), name='diagnosticreport_update'),
    # url(r'^patient/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='patient_detail'),

    url(r'^encounter/$', EncounterListView.as_view(), name='encounter_list'),
    url(r'^encounter/new/$', EncounterCreateView.as_view(), name='encounter_add'),
    url(r'^encounter/(?P<pk>\d+)/update/$', EncounterUpdateView.as_view(), name='encounter_update'),
    # url(r'^patient/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='patient_detail'),

    url(r'^healthcareservice/$', HealthcareServiceListView.as_view(), name='healthcareservice_list'),
    url(r'^healthcareservice/new/$', HealthcareServiceCreateView.as_view(), name='healthcareService_add'),
    url(r'^healthcareservice/(?P<pk>\d+)/update/$', HealthcareServiceUpdateView.as_view(), name='healthcareservice_update'),
    # url(r'^patient/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='patient_detail'),

    url(r'^location/$', LocationListView.as_view(), name='location_list'),
    url(r'^location/new/$', LocationCreateView.as_view(), name='location_add'),
    url(r'^location/(?P<pk>\d+)/update/$', LocationUpdateView.as_view(), name='location_update'),
    # url(r'^patient/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='patient_detail'),

    url(r'^patient/$', PatientListView.as_view(), name='patient_list'),
    url(r'^patient/new/$', PatientCreateView.as_view(), name='patient_add'),
    url(r'^patient/(?P<pk>\d+)/update/$', PatientUpdateView.as_view(), name='patient_update'),   
    url(r'^patient/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='patient_detail'),   
     
    url(r'^practitioner/$', PractitionerListView.as_view(), name='practitioner_list'),
    url(r'^practitioner/new/$', PractitionerCreateView.as_view(), name='practitioner_add'),
    url(r'^practitioner/(?P<pk>\d+)/update/$', PractitionerUpdateView.as_view(), name='practitioner_update'),
    # url(r'^patient/(?P<pk>\d+)/detail/$', PatientDetailView.as_view(), name='patient_detail'),
    
    url(r'^dashboard/$', views.ubah_status_dokter, name='dashboard'), 
    url(r'^pengaturan/$', views.ubah_status_dokter, name='pengaturan'),   
    url(r'^daftartabel/$', daftarTabelListView.as_view(), name='daftar_tabel'),
    # url(r'^dashboard/$', 'formdemografi.views.search', name='doctor_homepage'),    

    url(r'^pendaftaran/$', daftarTabelListView.as_view(), name='pendaftaran'), 


    # url(r'^teskon/$', views.internet_on, name='kon'),

]

formdemografi/models.py
from __future__ import unicode_literals
# import uuid
from django.db import models
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

# example django-queued-storage
# from queued_storage.fields import QueuedFileField
# from queued_storage.backends import QueuedStorage
# queued_s3storage = QueuedStorage(
#     'django.core.files.storage.FileSystemStorage',
#     'storages.backends.s3boto.S3BotoStorage', 
#     task='queued_storage.tasks.TransferAndDelete')

# class MyModel(models.Model):
#     my_file = models.FileField(upload_to='files', storage=queued_s3storage)

###############################

# class petugasrekammedis(models.Model):
#     user = models.OneToOneField(User)
#     SedangPraktek = models.BooleanField( # 
#         default = False)

# class petugaspendaftaran(models.Model):
#    user = models.OneToOneField(User)

# user = User.objects.create_user(username='dokterA',
#                                 password='8semutapikacau')

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

# ++++++++++++++++++++++++++++++++++++++++++++

class statusDokterTersedia(models.Model):
    id_user = models.ForeignKey('auth.User')
    KETERSEDIAAN_CHOICES = (
        ("off", 'Sedang tidak praktek'),
        ("on", 'Sedang praktek'),
    )
    SedangPraktek = models.CharField(
        choices = KETERSEDIAAN_CHOICES,
        max_length = 25,
        default=False,
        verbose_name = "Status anda",
        blank = True)
    date_created = models.DateTimeField(
        primary_key = True,
        default=timezone.now)

    def status_dokter(self):
        current_user = request.user
        return self.current_user

class tabel_sinkronisasi_cloud(models.Model):
    id_transaksi_cloud = models.CharField(
        max_length = 20,
        primary_key=True)
    date_received = models.DateTimeField(
        default=timezone.now)
    tbl_client = models.OneToOneField(
        'tabel_sinkronisasi_client',
        # on_delete=models.CASCADE,
        # primary_key=True,
    )

class tabel_sinkronisasi_client(models.Model):
    id_user = models.ForeignKey('auth.User')
    # patient = models.ForeignKey('Patient', null=True, on_delete=models.CASCADE)
    id_transaksi_client = models.CharField(
        primary_key=True,
        max_length = 50,)
    status_sinkronisasi = models.CharField(
        default='0',
        max_length = 1)
    status_edit = models.CharField(
        default='0',
        max_length = 1)
    # no_rekam_medis = models.CharField(
    #     max_length = 50,
    #     unique = True)    
    date_created = models.DateTimeField(
        default=timezone.now)
    # date_uploaded belum edit nyambung sama script
    date_uploaded = models.DateTimeField(
        default=timezone.now)
    
    class Meta:
        unique_together = (("id_user", "id_transaksi_client"),)

    def stat_sinkron(self):
        status_sinkronisasi = request.user
        return self.current_user

class arsip(models.Model):
    # id_user = models.ForeignKey('auth.User')
    no_rekam_medis = models.CharField(
        max_length = 50,
        unique = True)  
    waktu_saat_data_akan_diubah = models.DateTimeField(
        default=timezone.now)

# hanya bisa dicreate sama FO, dilihat oleh dokter
class antrian(models.Model):
    # karyawan_pendaftaran = models.ForeignKey('auth.User')
    dokter_tujuan = models.ForeignKey('Practitioner', null=True, on_delete=models.CASCADE)
    waktu = models.DateTimeField(
        default=timezone.now)
    no_antrian = models.AutoField(primary_key=True)
    
    # def __str__(self):
    #     return self.title
    def antrian_sekarang(self):
        no_antrian = self.no_antrian
        return self.no_antrian

# ++++++++++++++++++++++++++++++++++++++++++++
# ManyToManyField
class pasien_dari_dokter(models.Model):
    pasien = models.ForeignKey('Patient', related_name='pasiendokter', null=True, on_delete=models.CASCADE)
    dokter = models.ForeignKey('Practitioner', related_name='pasiendokter', null=True, on_delete=models.CASCADE)
    
    def __unicode__(self):
        # return "%s merupakan pasien %s" % (self.pasien, self.dokter)
        return "%s memiliki pasien %s" % (self.dokter, self.pasien)

# ++++++++++++++++++++++++++++++++++++++++++++

# class TimeStampedModel(models.Model):
#     created = models.DateTimeField(auto_now_add=True)
#     modified = models.DateTimeField(auto_now=True)
#     class Meta:
#         abstract = True

# ++++++++++++++++++++++++++++++++++++++++++++

class Condition(models.Model):
    patient = models.ForeignKey('Patient', null=True, on_delete=models.CASCADE)
    # id_pembuat = models.ForeignKey('auth.User')

    """Use to record detailed information about conditions, problems or
    diagnoses recognized by a clinician. There are many uses
    including: recording a diagnosis during an encounter; populating
    a problem list or a summary statement, such as a discharge
    summary.If the element is present, it must have either a @value,
    an @id, or extensionsEstimated or actual date or date-time the
    condition began, in the opinion of the clinician.The date or
    estimated date that the condition resolved or went into
    remission. This is called "abatement" because of the many
    overloaded connotations associated with "remission" or
    "resolution" - Conditions are never really resolved, but they
    can abate."""
    description = ("Detailed information about conditions, problems or diagnoses")

    # CATEGORY_CHOICES = (
    #     ('complaint', 'Keluhan'),
    #     ('symptom', 'Gejala'),
    #     ('finding', 'Penemuan'),
    #     ('diagnosis', 'Diagnosis'),
    # )
    CATEGORY_CHOICES = (
        ("complaint", 'Keluhan'),
        ("symptom", 'Gejala'),
        ("finding", 'Penemuan'),
        ("diagnosis", 'Diagnosis'),
    )

    # identifier = models.CharField( # External Ids for this condition
    #     help_text = "",
    #     max_length = 30,
    #     blank = False)
    # identifier = form 0..* (Identifier DONE)
    # patient  # Who has the condition? ref patient
    # encounter # Encounter when condition first asserted : ref encounter
    dateRecorded = models.DateTimeField( # When first entered
        auto_now = True,
        blank = False)
    code = models.CharField( # Identification of the condition, problem or diagnosis 
        # choices = Condition/Problem/Diagnosis Codes
        help_text = "kode",
        max_length = 20,
        blank = False)
    category = models.CharField(
        choices = CATEGORY_CHOICES,
        help_text = "",
        max_length = 20,
        blank = True)
# evidence = form 0..* (Evidence DONE)
    bodySite = models.CharField( # Anatomical location, if relevant | SNOMED CT Body Structures
        help_text = "",
        max_length = 245,
        blank = True)
    notes = models.TextField(blank=True)
    history = HistoricalRecords()

class DiagnosticReport(models.Model):
    # id_pembuat = models.ForeignKey('auth.User')
    description = ("A Diagnostic report - a combination of request information, atomic results, images, interpretation, as well as formatted reports")

    DIAGNOSTIC_REPORT_STATUS_CHOICES = (
        ('registered', mark_safe(u'<em></em> | ')), # The existence of the report is registered, but there is nothing yet available.
        ('partial', mark_safe(u'<em></em> | ')), # This is a partial (e.g. initial, interim or preliminary) report: data in the report may be incomplete or unverified.
        ('final', mark_safe(u'<em></em> | ')), # The report is complete and verified by an authorized person.
        ('corrected', mark_safe(u'<em></em> | ')), # The report has been modified subsequent to being Final, and is complete and verified by an authorized person. New content has been added, but existing content hasn't changed
        ('appended', mark_safe(u'<em></em> | ')), # The report has been modified subsequent to being Final, and is complete and verified by an authorized person. New content has been added, but existing content hasn't changed.
        ('cancelled', mark_safe(u'<em></em> | ')), # The report is unavailable because the measurement was not started or not completed (also sometimes called "aborted").
        ('entered-in-error', mark_safe(u'<em></em> | ')), # The report has been withdrawn following a previous final release.
    )
    # identifier = form 0..* (identifier DONE) Id for external references to this report
    status = models.CharField( #
        choices = DIAGNOSTIC_REPORT_STATUS_CHOICES,
        help_text = "",
        max_length = 20,
        blank = False)
    category= models.CharField( # Service category 
        # choices = Diagnostic Service Section Codes
        help_text = "",
        max_length = 20,
        blank = True)
    code = models.CharField( # Name/Code for this diagnostic report 
        # choices = LOINC Diagnostic Report 
        help_text = "",
        max_length = 20,
        blank = False)
    # subject = ref 1..1 (patient, location) The subject of the report, usually, but not always, the patient
    # encounter = ref 0..1 (encounter) Health care event when test ordered
# effective[x] :1..1(   Clinically Relevant time/time-period for report
    effectiveDateTime = models.DateTimeField( # 
        help_text = "",
        blank = False)
    # effectivePeriod = form 1..1 (Period DONE)
# )
    issued = models.DateTimeField( # DateTime this version was released
        default=timezone.now)

formdemografi/templates/formdemografi/codeableconcept_add.html
<!DOCTYPE html>
<html>
<head>
    <title>Tambah Codeable Concept</title>
    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.formset.js"></script>
    <script type="text/javascript">
        $(function() {
            $(".inline.{{ codeableconcept_coding_formset.prefix }}").formset({
                prefix: "{{ codeableconcept_coding_formset.prefix }}",
            })
        })
    </script>
</head>

<body>
    <div>
        <h1>Add Codeable Concept</h1>
        <form action="." method="post">
            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
            <fieldset>
                <legend>Coding</legend>
                {{ codeableconcept_coding_formset.management_form }}
                {{ codeableconcept_coding_formset.non_form_errors }}
                {% for form in codeableconcept_coding_formset %}
                    {{ form.id }}
                    <div class="inline {{ codeableconcept_coding_formset.prefix }}">
                        {{ form.system.errors }}
                        {{ form.system.label_tag }}
                        {{ form.system }}
                        {{ form.version.errors }}
                        {{ form.version.label_tag }}
                        {{ form.version }}
                        {{ form.code.errors }}
                        {{ form.code.label_tag }}
                        {{ form.code }}
                        {{ form.display.errors }}
                        {{ form.display.label_tag }}
                        {{ form.display }}
                        {{ form.userSelected.errors }}
                        {{ form.userSelected.label_tag }}
                        {{ form.userSelected }}
                    </div>
                {% endfor %}
            </fieldset>

            <input type="submit" value="Add patient" class="submit" />
        </form>
    </div>
</body>
</html>

formdemografi/templates/formdemografi/condition_list.html
{% extends 'formdemografi/ui_base.html' %}

{% block content %}
    <p><a href="{% url 'formdemografi:condition_add' %}">New</a></p> 
    {% for condition in condition_list %}
    <p>{{ condition.dateRecorded }} | {{ condition.code }} |
    <a href="{% url 'formdemografi:condition_detail' condition.pk %}">Detail</a> | 
    <a href="{% url 'formdemografi:condition_update' condition.pk %}">Ubah</a> </p>
    {% endfor %}

{% endblock %}
 

formdemografi/templates/formdemografi/daftar_tabel.html
{% extends 'formdemografi/ui_base.html' %}

{% block content %}
    <h1>Daftar Antrian Pasien</h1>
    <!-- list pasien -->

    <table>
    	<thead>
    		<tr>
    			<th>Pengguna</th>
    			<th>Ketersediaan</th>
                <th>Tanggal</th>
    		</tr>
    	</thead>
        {% for statusDokterTersedia in statusdoktertersedia_list %}
    	<tr>
    		<td>{{statusDokterTersedia.id_user.username}}</td>
    		<td>{{ statusDokterTersedia.SedangPraktek }}</td>
            <td>{{statusDokterTersedia.date_created}}</td>
    	</tr>
        {% endfor %}
    </table>

    

{% endblock %}
 

formdemografi/templates/formdemografi/diagnosticreport_add.html
<!DOCTYPE html>
<html>
<head>
    <title>Laporan Diagnosa</title>
    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.formset.js"></script>
    <script type="text/javascript">
        $(function() {
            $(".inline.{{ diagnosticreport_codeableconcept_formset.prefix }}").formset({
                prefix: "{{ diagnosticreport_codeableconcept_formset.prefix }}",
            })
            $(".inline.{{ diagnosticreport_attachment_formset.prefix }}").formset({
                prefix: "{{ diagnosticreport_attachment_formset.prefix }}",
            })
        })
    </script>
</head>

<body>
    <div>
        <h1>Tambah Laporan Diagnosa</h1>
        <form action="." method="post">
            {% csrf_token %}
            <div>
                {{ form.as_p }}
            </div>
            <fieldset>
                <legend>Codeable Concept</legend>
                {{ diagnosticreport_codeableconcept_formset.management_form }}
                {{ diagnosticreport_codeableconcept_formset.non_form_errors }}
                {% for form in pdiagnosticreport_codeableconcept_formset %}
                    {{ form.id }}
                    <div class="inline {{ diagnosticreport_codeableconcept_formset.prefix }}">
                        {{ form.text.errors }}
                        {{ form.text.label_tag }}
                        {{ form.text }}
                    </div>
                {% endfor %}
            </fieldset>
            <fieldset>
                <legend>Attachment</legend>
                {{ diagnosticreport_attachment_formset.management_form }}
                {{ diagnosticreport_attachment_formset.non_form_errors }}
                {% for form in diagnosticreport_attachment_formset %}
                    {{ form.id }}
                    <div class="inline {{ diagnosticreport_attachment_formset.prefix }}">
                        {{ form.url.errors }}
                        {{ form.url.label_tag }}
                        {{ form.url }}
                        {{ form.title.errors }}
                        {{ form.title.label_tag }}
                        {{ form.title }}
                    </div>
                {% endfor %}
            </fieldset>
            <input type="submit" value="Simpan" class="submit" />
        </form>
    </div>
</body>
</html>

formdemografi/templates/formdemografi/location_list.html
<!DOCTYPE html>
<html>
	<head>
        <meta charset="utf-8" />
		<title>location_list</title>
	</head>
	<body>
    <p><a href="{% url 'formdemografi:location_add' %}">New</a></p> 
    {% for location in location_list %}
    <p><a href="{% url 'formdemografi:location_update' location.pk %}">{{ location.name }}</a> | {{ location.description }} </p>
    {% endfor %}
	</body>
</html>

formdemografi/templates/formdemografi/patient_detail.html
{% extends 'formdemografi/ui_pendaftaran.html' %}


{% block content %}
    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.formset.js"></script>
    <script type="text/javascript">
    </script>

<body>
    <div>
        <h1>Detail Data Demografi Pasien</h1>
        <ul class="list-group">
            <li class="list-group-item"><b>Status Aktif:</b> {{patient.active}}</li>
            <li class="list-group-item"><b>Jenis Kelamin:</b> {{patient.gender}}</li>
            <li class="list-group-item"><b>Tanggal Lahir:</b> {{patient.birthDate}}</li>
            <li class="list-group-item"><b>Status Pernikahan:</b> {{patient.maritalStatus}}</li>
            <li class="list-group-item"><b>Bahasa:</b> {{patient.language}}</li>
            <li class="list-group-item">
                <b style="text-align:center;">Identifikasi</b>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Tipe</th>
                            <th>Nomor ID</th>
                        </tr>
                    </thead>
                    {% for a in patient.identifier_set.all %}
                    <tr>
                        <td>{{a.Type}}</td>
                        <td>{{a.Value}}</td>
                    </tr>
                    {% endfor %}
                </table>   
            </li>
            <li class="list-group-item">
                <b>Nama</b>
                <table class="table table-hover">   
                    <thead>
                        <tr>
                            <th>Nama Lengkap</th>
                            <th>Nama Depan</th>
                            <th>Nama Belakang</th>
                        </tr>
                    </thead>
                    {% for b in patient.humanname_set.all %}
                    <tr>
                        <td>{{b.text}}</td>
                        <td>{{b.given}}</td>
                        <td>{{b.family}}</td>
                    </tr>
                    {% endfor %}
                </table>   
            </li>
            <li class="list-group-item">
                <b>Nomor Telepon</b> 
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Jenis</th>
                        <th>Nomor</th>
                    </tr>
                    </thead>
                        {% for c in patient.contactpoint_set.all %}
                        <tr>
                            <td>{{c.system}}</td>
                            <td>{{c.Value}}</td>
                        </tr>
                        {% endfor %}
                </table>
            </li>
            <li class="list-group-item">
                <b>Alamat</b> 
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Tipe</th>
                        <th>Teks</th>
                        <th>Jalan</th>
                        <th>Kota</th>
                        <th>Distrik</th>
                        <th>Negara (state)</th>
                        <th>Kode Pos</th>
                        <th>Negara</th>
                    </tr>
                    </thead>
                        {% for d in patient.address_set.all %}
                        <tr>
                            <td>{{d.Type}}</td>
                            <td>{{d.text}}</td>
                            <td>{{d.line}}</td>
                            <td>{{d.city}}</td>
                            <td>{{d.district}}</td>
                            <td>{{d.state}}</td>
                            <td>{{d.postalCode}}</td>
                            <td>{{d.country}}</td>
                        </tr>
                        {% endfor %}
                </table>
            </li>
            <li class="list-group-item">
                <b>Status Meninggal:</b> {{patient.deceasedBoolean}} <br>
                <b>Tanggal Meninggal:</b> {{patient.deceasedDateTime}}
            </li>
        </ul>
    
        <p>
        <a class="btn btn-info" href="{% url 'formdemografi:patient_update' patient.pk %}">Ubah</a>
        <a class="btn btn-info" href="{% url 'formdemografi:patient_list' %}">Daftar Pasien</a>
        </p>
        
    </div>
</body>

{% endblock %}

formdemografi/templates/formdemografi/post_edit.html
{% extends 'formdemografi/base.html' %}


{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

formdemografi/templates/formdemografi/practitioner_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>practitioner_list</title>
    </head>
    <body>
    <p><a href="{% url 'formdemografi:practitioner_add' %}">New</a></p> 
    {% for practitioner in practitioner_list %}
    <p><a href="{% url 'formdemografi:practitioner_update' practitioner.pk %}">{{ practitioner.id }}</a> <!-- | {{ practitioner.description }} --> </p>
    {% endfor %}
    </body>
</html>

formdemografi/templates/formdemografi/ui_pendaftaran.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Rekam Medis Elektronik</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/csss.css' %}">
    <script type="text/javascript" src="{% static 'js/jss.js' %}"></script>

<nav class="navbar navbar-toggleable-md navbar-default fixed-top" data-spy="affix">
    <div id="containernav">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Rekam Medis Elektronik</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'formdemografi:patient_list' %}">Riwayat Kegiatan</a></li>
                <li><a href="{% url 'formdemografi:patient_add' %}">Pendaftaran Pasien Baru</a></li>
                <li><a href="{% url 'formdemografi:patient_list' %}">Tambah Antrian</a></li>
                <li><a>Selamat Datang, {{request.user.username}}!</a></li> 
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <div class="dropdown">
                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="glyphicon glyphicon-user">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu">
                        <li><a href="#"><span class="glyphicon glyphicon-cog"></span> Pengaturan</a></li>
                        <li><a href="{% url 'formdemografi:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Log Out</a></li>
                    </ul>
                </div>         
            </ul>
        </div>
    </div>
</nav>

<div class="row-offcanvas row-offcanvas-left">
    <div id="sidebar" class="sidebar-offcanvas">
        <div class="col-md-12">
            <ul class="nav nav-pills nav-stacked" id="navy">
                <li class="active"><a href="#">Dashboard Pendaftaran</a></li>
            </ul>
            <br>
            <div class="panel panel-info">
                <div class="panel-heading">Sync Status</div>
                <div class="panel-body">
                    <p style="font-size:13px">Status: </p>
                    <p style="font-size:13px">Sinkronisasi Terakhir: </p>
                    <p style="font-size:13px">Lokasi: </p>
                    <p style="font-size:13px">Rumah Sakit: </p>
                    <p style="font-size:13px">Poli: </p>
                </div>
            </div>
        </div>
    </div>    
</div>

</head>


<body>

    <div class="container-fluid">
        <div class="well">
            {% block content %}
                            
            {% endblock %}
        </div>
    </div>

</body>

</html>